stages:
 patchify_images:
    cmd: python3 src/split_util/img_split.py --base-json "src/split_util/split_config.json" --sizes ${dataset.sizes} --gaps ${dataset.gaps}
    deps:
    - src/split_util/img_split.py
    - src/split_util/split_config.json
    - data/labeled_dataset
    params:
    - dataset.sizes
    - dataset.gaps
    outs:
    - data/patchified_dataset
 data_split:
   cmd: python3 src/train_test_split.py --metadata-file ${split.metadata-file} --method ${split.method} --ratio ${split.ratio} --seed ${split.seed}
   deps:
   - src/train_test_split.py
   - data/metadata_train.csv
   params:
   - split.metadata-file
   - split.ratio
   - split.method
   - split.seed
   outs:
   - data/split/
 train:
    cmd: python3 src/train.py --learning-rate ${optimizer.learning_rate} --max-epochs ${optimizer.max_epochs}
    deps:
    - src/train.py
    #- model_config
    #- model_weights
    - data/patchified_dataset
    - data/split
    - src/MAFAT_Dataset.py
    params:
    - optimizer.learning_rate
    - optimizer.max_epochs
    outs:
    - model.pkl
    metrics:
    - results/train/metrics.json:
        cache: false
    plots:
    - results/train/plots:
        cache: false
#  evaluate:
#    cmd: python3 src/evaluate.py
#    deps:
#    - data/test_data
#    - models/model.pkl
#    - src/evaluate.py
#    params:
#    - base
#    - evaluate
#    metrics:
#    - results/evaluate/metrics.json:
#        cache: false
#    plots:
#    - results/evaluate/plots:
#        cache: false