dataset:
  sizes: 640
  gaps: 320
split:
  metadata-file: /workspaces/MAFAT-Satellite-Vision-Challenge/data/metadata_train.csv
  ratio: 0.2
  method: AOI
  seed: 42
  output-dir: /workspaces/MAFAT-Satellite-Vision-Challenge/data/splits
model:
  frozen_stages: 1
  pretrained: work_dirs/pretrain/re_resnet50_c8_batch256-25b16846.pth
optimizer:
  learning_rate: 0.001
  max_epochs: 4
