angle_version: le90
checkpoint_config:
  interval: 1
data:
  samples_per_gpu: 2
  test:
    ann_file: labelTxt
    data_root: ./val
    img_prefix: images
    pipeline:
    - type: LoadImageFromFile
    - flip: false
      img_scale: 
      - 1024
      - 1024
      transforms:
      - type: RResize
      - mean:
        - 795.0878
        - 795.0878
        - 795.0878
        std:
        - 460.0955
        - 460.0955
        - 460.0955
        to_rgb: true
        type: Normalize
      - size_divisor: 32
        type: Pad
      - type: DefaultFormatBundle
      - keys:
        - img
        type: Collect
      type: MultiScaleFlipAug
    type: MAFATDataset
    version: le90
  train:
    ann_file: labelTxt
    data_root: ./train
    img_prefix: images
    pipeline:
    - type: LoadImageFromFile
    - type: LoadAnnotations
      with_bbox: true
    - img_scale:
      - 1024
      - 1024
      type: RResize
    - direction:
      - horizontal
      - vertical
      - diagonal
      flip_ratio:
      - 0.25
      - 0.25
      - 0.25
      type: RRandomFlip
      version: le90
    - angles_range: 180
      auto_bound: false
      rect_classes:
      - 9
      - 11
      rotate_ratio: 0.5
      type: PolyRandomRotate
      version: le90
    - mean:
      - 795.0878
      - 795.0878
      - 795.0878
      std:
      - 460.0955
      - 460.0955
      - 460.0955
      to_rgb: true
      type: Normalize
    - size_divisor: 32
      type: Pad
    - type: DefaultFormatBundle
    - keys:
      - img
      - gt_bboxes
      - gt_labels
      type: Collect
    type: MAFATDataset
    version: le90
  val:
    ann_file: labelTxt
    data_root: ./val
    img_prefix: images
    pipeline:
    - type: LoadImageFromFile
    - flip: false
      img_scale:
      - 1024
      - 1024
      transforms:
      - type: RResize
      - mean:
        - 795.0878
        - 795.0878
        - 795.0878
        std:
        - 460.0955
        - 460.0955
        - 460.0955
        to_rgb: true
        type: Normalize
      - size_divisor: 32
        type: Pad
      - type: DefaultFormatBundle
      - keys:
        - img
        type: Collect
      type: MultiScaleFlipAug
    type: MAFATDataset
    version: le90
  workers_per_gpu: 2
data_root: ./
dataset_type: MAFATDataset
device: cuda
dist_params:
  backend: nccl
evaluation:
  interval: 2
  metric: mAP
gpu_ids: 
- 0
- 1
- 2
img_norm_cfg:
  mean:
  - 795.0878
  - 795.0878
  - 795.0878
  std:
  - 460.0955
  - 460.0955
  - 460.0955
  to_rgb: true
  type: Normalize
load_from: redet_re50_fpn_1x_dota_ms_rr_le90-fc9217b5.pth
log_config:
  hooks:
  - type: TextLoggerHook
  - type: TensorboardLoggerHook
  interval: 2
log_level: INFO
lr_config:
  policy: step
  step:
  - 8
  - 11
  warmup: null
  warmup_iters: 500
  warmup_ratio: 0.3333333333333333
model:
  backbone:
    depth: 50
    frozen_stages: 1
    num_stages: 4
    out_indices:
    - 0
    - 1
    - 2
    - 3
    pretrained: work_dirs/pretrain/re_resnet50_c8_batch256-25b16846.pth
    style: pytorch
    type: ReResNet
  neck:
    in_channels:
    - 256
    - 512
    - 1024
    - 2048
    num_outs: 5
    out_channels: 256
    type: ReFPN
  roi_head:
    bbox_head:
    - bbox_coder:
        angle_range: le90
        edge_swap: true
        norm_factor: 2
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 0.1
        - 0.1
        - 0.2
        - 0.2
        - 1
        type: DeltaXYWHAHBBoxCoder
      fc_out_channels: 1024
      in_channels: 256
      loss_bbox:
        beta: 1.0
        loss_weight: 1.0
        type: SmoothL1Loss
      loss_cls:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: false
      num_classes: 13
      reg_class_agnostic: true
      roi_feat_size: 7
      type: RotatedShared2FCBBoxHead
    - bbox_coder:
        angle_range: le90
        edge_swap: true
        norm_factor: null
        proj_xy: true
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 0.05
        - 0.05
        - 0.1
        - 0.1
        - 0.5
        type: DeltaXYWHAOBBoxCoder
      fc_out_channels: 1024
      in_channels: 256
      loss_bbox:
        beta: 1.0
        loss_weight: 1.0
        type: SmoothL1Loss
      loss_cls:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: false
      num_classes: 13
      reg_class_agnostic: false
      roi_feat_size: 7
      type: RotatedShared2FCBBoxHead
    bbox_roi_extractor:
    - featmap_strides:
      - 4
      - 8
      - 16
      - 32
      out_channels: 256
      roi_layer:
        output_size: 7
        sampling_ratio: 0
        type: RoIAlign
      type: SingleRoIExtractor
    - featmap_strides:
      - 4
      - 8
      - 16
      - 32
      out_channels: 256
      roi_layer:
        clockwise: true
        num_orientations: 8
        num_samples: 2
        out_size: 7
        type: RiRoIAlignRotated
      type: RotatedSingleRoIExtractor
    num_stages: 2
    stage_loss_weights:
    - 1
    - 1
    type: RoITransRoIHead
    version: le90
  rpn_head:
    anchor_generator:
      ratios:
      - 0.5
      - 1.0
      - 2.0
      scales:
      - 8
      strides:
      - 4
      - 8
      - 16
      - 32
      - 64
      type: AnchorGenerator
    bbox_coder:
      target_means:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      target_stds:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      type: DeltaXYWHBBoxCoder
    feat_channels: 256
    in_channels: 256
    loss_bbox:
      beta: 0.1111111111111111
      loss_weight: 1.0
      type: SmoothL1Loss
    loss_cls:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: true
    type: RotatedRPNHead
    version: le90
  test_cfg:
    rcnn:
      max_per_img: 2000
      min_bbox_size: 0
      nms:
        iou_thr: 0.1
      nms_pre: 2000
      score_thr: 0.05
    rpn:
      max_per_img: 2000
      min_bbox_size: 0
      nms:
        iou_threshold: 0.7
        type: nms
      nms_pre: 2000
  train_cfg:
    rcnn:
    - assigner:
        ignore_iof_thr: -1
        iou_calculator:
          type: BboxOverlaps2D
        match_low_quality: false
        min_pos_iou: 0.5
        neg_iou_thr: 0.5
        pos_iou_thr: 0.5
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: true
        neg_pos_ub: -1
        num: 512
        pos_fraction: 0.25
        type: RandomSampler
    - assigner:
        ignore_iof_thr: -1
        iou_calculator:
          type: RBboxOverlaps2D
        match_low_quality: false
        min_pos_iou: 0.5
        neg_iou_thr: 0.5
        pos_iou_thr: 0.5
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: true
        neg_pos_ub: -1
        num: 512
        pos_fraction: 0.25
        type: RRandomSampler
    rpn:
      allowed_border: 0
      assigner:
        gpu_assign_thr: 200
        ignore_iof_thr: -1
        match_low_quality: true
        min_pos_iou: 0.3
        neg_iou_thr: 0.3
        pos_iou_thr: 0.7
        type: MaxIoUAssigner
      debug: false
      pos_weight: -1
      sampler:
        add_gt_as_proposals: false
        neg_pos_ub: -1
        num: 256
        pos_fraction: 0.5
        type: RandomSampler
    rpn_proposal:
      max_per_img: 2000
      min_bbox_size: 0
      nms:
        iou_threshold: 0.7
        type: nms
      nms_pre: 2000
  type: ReDet
mp_start_method: fork
opencv_num_threads: 0
optimizer:
  lr: 0.001
  momentum: 0.9
  type: SGD
  weight_decay: 0.0001
optimizer_config:
  grad_clip:
    max_norm: 35
    norm_type: 2
resume_from: null
runner:
  max_epochs: 4
  type: EpochBasedRunner
seed: 0
test_pipeline:
- color_type: unchanged
  type: LoadImageFromFilePIL
- flip: false
  img_scale: 
  - 1024
  - 1024
  transforms:
  - type: RResize
  - mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
    type: Normalize
  - size_divisor: 32
    type: Pad
  - type: DefaultFormatBundle
  - keys:
    - img
    type: Collect
  type: MultiScaleFlipAug
train_pipeline:
- color_type: unchanged
  type: LoadImageFromFilePIL
- type: LoadAnnotations
  with_bbox: true
- img_scale: 
  - 1024
  - 1024
  type: RResize
- direction:
  - horizontal
  - vertical
  - diagonal
  flip_ratio:
  - 0.25
  - 0.25
  - 0.25
  type: RRandomFlip
  version: le90
- angles_range: 180
  auto_bound: false
  rect_classes:
  - 9
  - 11
  rotate_ratio: 0.5
  type: PolyRandomRotate
  version: le90
- mean:
  - 123.675
  - 116.28
  - 103.53
  std:
  - 58.395
  - 57.12
  - 57.375
  to_rgb: true
  type: Normalize
- size_divisor: 32
  type: Pad
- type: DefaultFormatBundle
- keys:
  - img
  - gt_bboxes
  - gt_labels
  type: Collect
work_dir: ./tutorial_exps
